### ISSUE TITLE
Can not work...

### ISSUE THREAD

**Issue by cloverhsc** [jumpkick/graphviz-preview#20]
After install graphviz-preview and try test. The preview always a white view.
So dose something need to setting?
PS: Ubuntu 14.04 + dot - graphviz version 2.36.0
![graphviz_preview](https://cloud.githubusercontent.com/assets/6084882/13660049/a8f33d46-e6c1-11e5-8cb7-db44f4675a52.jpg)

**Comment by elleryq** [comment]
It should be fixed in 46323646fe3c8b44062bc62eebb50b20bff9310d and bcfe1e939599927425a4d26991965427fb90327f

**Comment by jumpkick** [comment]
I haven't released your patches because I still get errors, last one was something about the properties on "dispose" on line 40 of one of the coffee scripts.   (kind of wrecked by a cold right now, so didn't dig into it more)

**Comment by elleryq** [comment]
@jumpkick I don't get any error.  Is there anything I can help with?

**Comment by e0725675** [comment]
accidently created a duplicate issue. #25

**Comment by wkpalan** [comment]
+1

**Comment by wkpalan** [comment]
I think I might have a solution. This builds on the fixes elleryq has proposed. After making the changes mentioned in his fixes. I have added some changes

Using iframe does not pass the Content policy for the newer node modules. This stems from the index.html from the core Atom files. I have taken the example from html-preview package and have used webview instead of iframe in graphviz-preview-view.coffee.

This allows us to set the scripts and styles to be run from the same origin.

commit is [here](https://github.com/jumpkick/graphviz-preview/pull/29)

**Comment by jumpkick** [comment]
@wkpalan, it appears your patch has fixed the issue back to the last semi-working state (before the atom API changes broke live refreshing), I'll push this out as a release and credit both elleryq and yourself.  Thanks.

**Comment by wkpalan** [comment]
You are welcome, and **thanks** for making this available in the first place. This is has been very helpful at work for me. 

I didn't quite understand what live refreshing means, but for my purpose it is refreshing as soon as I save the file. My habit of frequent saving seems to work well for me. For some of the larger graphs I work with, not having live refresh seems to actually helps.

**Comment by deftdawg** [comment]
When I first got it going, it used to refresh as soon as you stopped typing on a line.  That was helpful in seeing syntax errors before one saved.   If you open a new file, open preview, type some dot, close preview and reopen it, it will load without saving...    Anyway, the onchange event hook API probably changed or something... lol

You're most welcome, hacked this together because I needed something to plot graphs at work almost 2 years ago.  Don't work there anymore & haven't felt the motivation to try to keep pace with Atom's ever changing APIs, so patches are always welcome, it's also nice to know others can get some benefit from it. :D 

1.7.0 is released now, so I'm closing this.
